### ISSUE TITLE
Unable to load DLL 'libSkiaSharp' on iOS

### ISSUE THREAD

**Issue by BigGiantHead** [SrejonKhan/AsyncImageLibrary#3]
Hello,

When I build for iOS using this package I get the following error:

DllNotFoundException: Unable to load DLL 'libSkiaSharp'. Tried the load the following dynamic libraries: Unable to load dynamic library '/libSkiaSharp' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen(/libSkiaSharp, 0x0005): tried: '/libSkiaSharp' (errno=2), '/private/preboot/Cryptexes/OS/libSkiaSharp' (errno=2), '/libSkiaSharp' (errno=2)

Please help.

**Comment by LeshM** [comment]
any luck with this? I get it too

**Comment by SrejonKhan** [comment]
Could you please add `__IOS__`and `__UNIFIED__` to the Scripting Define Symbols and try to build again? Let me know the update. 

I will update SkiaSharp's version to the latest one (2.88.3), it's been a long time since we are using an older version (2.80.3).

**Comment by LeshM** [comment]
> Could you please add `__IOS__`and `__UNIFIED__` to the Scripting Define Symbols and try to build again? Let me know the update.
> 
> I will update SkiaSharp's version to the latest one (2.88.3), it's been a long time since we are using an older version (2.80.3).

I actually tried that already, didn't work.

**Comment by SrejonKhan** [comment]
Alright, thanks for the update.

**Comment by SrejonKhan** [comment]
Hello @LeshM, could you please try this `0.2.0-preview.1` version? Unfortunately, I don't have access to any Mac device right now, so couldn't build the XCode project. 

Right now, you can grab it from [OpenUPM ](https://openupm.com/packages/com.srejonkhan.asyncimagelibrary). 

Or, merge these in your `manifest.json` - 

```json
"scopedRegistries": [
  {
    "name": "package.openupm.com",
    "url": "https://package.openupm.com",
    "scopes": [
      "com.srejonkhan"
    ]
  }
]

"dependencies": {
    "com.srejonkhan.asyncimagelibrary": "0.2.0-preview.1"
}
```

Alternatively, you can try cloning this sandbox project and change the branch of the submodule to `develop` branch (instructions added)  - https://github.com/SrejonKhan/AsyncImageLibrary-Sandbox 

The build process would be exactly the same as you've tried earlier with Scripting Define Symbols. In case it fails, you may try tweaking the setting of `/AsyncImageLibrary/Dependencies/SkiaSharp/ios/native/libSkiaSharp.framework` if any mistakes were made from my side. Any changes/pull request is always appreciated.

**Comment by LeshM** [comment]
> Hello @LeshM, could you please try this `0.2.0-preview.1` version? Unfortunately, I don't have access to any Mac device right now, so couldn't build the XCode project.
> 
> Right now, you can grab it from [OpenUPM ](https://openupm.com/packages/com.srejonkhan.asyncimagelibrary).
> 
> Or, merge these in your `manifest.json` -
> 
> ```json
> "scopedRegistries": [
>   {
>     "name": "package.openupm.com",
>     "url": "https://package.openupm.com",
>     "scopes": [
>       "com.srejonkhan"
>     ]
>   }
> ]
> 
> "dependencies": {
>     "com.srejonkhan.asyncimagelibrary": "0.2.0-preview.1"
> }
> ```
> 
> Alternatively, you can try cloning this sandbox project and change the branch of the submodule to `develop` branch (instructions added) - https://github.com/SrejonKhan/AsyncImageLibrary-Sandbox
> 
> The build process would be exactly the same as you've tried earlier with Scripting Define Symbols. In case it fails, you may try tweaking the setting of `/AsyncImageLibrary/Dependencies/SkiaSharp/ios/native/libSkiaSharp.framework` if any mistakes were made from my side. Any changes/pull request is always appreciated.

I'm sorry but I'm afraid I can't, I'll need to reintegrate your package and then build for both Android & iOS using UCB (which takes about an hour each) just to find out if this works. I'm on a tight deadline and can't spare the time.

I do appreciate your work though, so thank you! 🙏

BTW I ended up using some Unity coroutine hack as a solution.

**Comment by SrejonKhan** [comment]
@LeshM No problem. Thank you too!
